name: Release Chart
on:
  push:
    branches:
      - main
jobs:
  Release:
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-release.yml@main
    permissions:
      contents: write
      actions: write
      deployments: write
      pages: write
    with:
      charts_dir: charts
